config/routes.rb
Contacts::Application.routes.draw do

  resources :contacts
  root :to => 'contacts#index'

end

app/models/contact.rb
class Contact <ActiveRecord::Base
  attr_accessible :name, :phone, :email # cм. seeds.rb file
  validates :name, :phone, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.all
  end
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])

    if @contact.save
      flash[:notice] = "Your contact was successfully created."
      redirect_to contacts_path
    else
      render :new
    end
  end

    def edit
      @contact = Contact.find(params[:id])
    end
  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(params[:contact])
      flash[:notice] = "Your contact was successsfully updated."
      redirect_to contacts_path
    else
      render :edit
    end

    def destroy
      @contact = Contact.find(params[:id])
      @contact.destroy
      flash[:notice] = "Your contact was successfully deleted."
      redirect_to contacts_path
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
    <div class="alert alert-error">
    <h3>Please correct these problems:</h3>
    <ul>
      <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </ul>
    </div>
<% end %>

<%= form_for @contact do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
    <%= f.label :email %>
    <%= f.text_field :email %><br><br>
    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
    <br>
<% end %>

app/views/contacts/edit.html.erb
<% provide :title, "Edit #{@contact.name}" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>
<p><%= link_to 'Add contact', contacts_path %></p>

app/views/contacts/index.html.erb
<% provide :title, 'Home' %>
<h1>Contacts</h1>
<p>Валидация!!!</p>
<%= link_to 'Main', contacts_path %>
<%= link_to 'Edit contact', edit_contact_path(@contact) %>
<h2>A user-contributed phone (and email) book.</h2>
<table class="table">
  <tr>
    <td>Name</td>
    <td>Phone</td>
    <td>Email</td>
  </tr>
  <% @contact.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact)%></td>
        <td><%= link_to 'Delete', contact, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<p><%= link_to 'Add contact', new_contact_path, :class => 'btn btn-primary' %></p>

app/views/contacts/new.html.erb
<% provide :title, "New contact" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>
<br>
<%= link_to 'Main', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
      <div class="alert alert-error"><%= flash[:alert] %></div>
  <% end %>

<%= yield %>
</div>
</body>
</html>